// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: pb.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ricart_RequestCS_FullMethodName = "/pb.Ricart/RequestCS"
	Ricart_ReleaseCS_FullMethodName = "/pb.Ricart/ReleaseCS"
)

// RicartClient is the client API for Ricart service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RicartClient interface {
	RequestCS(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	ReleaseCS(ctx context.Context, in *Release, opts ...grpc.CallOption) (*Response, error)
}

type ricartClient struct {
	cc grpc.ClientConnInterface
}

func NewRicartClient(cc grpc.ClientConnInterface) RicartClient {
	return &ricartClient{cc}
}

func (c *ricartClient) RequestCS(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Ricart_RequestCS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ricartClient) ReleaseCS(ctx context.Context, in *Release, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Ricart_ReleaseCS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RicartServer is the server API for Ricart service.
// All implementations must embed UnimplementedRicartServer
// for forward compatibility.
type RicartServer interface {
	RequestCS(context.Context, *Request) (*Response, error)
	ReleaseCS(context.Context, *Release) (*Response, error)
	mustEmbedUnimplementedRicartServer()
}

// UnimplementedRicartServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRicartServer struct{}

func (UnimplementedRicartServer) RequestCS(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestCS not implemented")
}
func (UnimplementedRicartServer) ReleaseCS(context.Context, *Release) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseCS not implemented")
}
func (UnimplementedRicartServer) mustEmbedUnimplementedRicartServer() {}
func (UnimplementedRicartServer) testEmbeddedByValue()                {}

// UnsafeRicartServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RicartServer will
// result in compilation errors.
type UnsafeRicartServer interface {
	mustEmbedUnimplementedRicartServer()
}

func RegisterRicartServer(s grpc.ServiceRegistrar, srv RicartServer) {
	// If the following call pancis, it indicates UnimplementedRicartServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ricart_ServiceDesc, srv)
}

func _Ricart_RequestCS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RicartServer).RequestCS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ricart_RequestCS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RicartServer).RequestCS(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ricart_ReleaseCS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Release)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RicartServer).ReleaseCS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ricart_ReleaseCS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RicartServer).ReleaseCS(ctx, req.(*Release))
	}
	return interceptor(ctx, in, info, handler)
}

// Ricart_ServiceDesc is the grpc.ServiceDesc for Ricart service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ricart_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Ricart",
	HandlerType: (*RicartServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestCS",
			Handler:    _Ricart_RequestCS_Handler,
		},
		{
			MethodName: "ReleaseCS",
			Handler:    _Ricart_ReleaseCS_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb.proto",
}
